
CREATE OR REPLACE FORCE EDITIONABLE VIEW "TREINA"."VZAPGRFDI" ("NROUNICO", "CODIGO", "DTCRIACAO", "DTFATUR", "TIPO", "STATUS", "PESOTOTAL", "GRUPOENTREGA", "TIPOENTREGA", "TABELAFRETE", "TRANSPORTADORA", "NOMEFANTASIA", "RAZAOSOCIAL", "UF", "CODTET", "CODPARCTRANSP", "CODOPL", "CODPARCUNIDPROD", "CODUF", "TZACONFERIDO", "ORIGEMPCT") AS 
  SELECT
        TO_CHAR(P.NUPCT, 'FM0000000000') || '-0000000000' NROUNICO,
        P.NUPCT CODIGO,
        P.TZADTCRIACAO DTCRIACAO,
--        N.DTENTSAI DTFATUR,
        NULL DTFATUR,
        'PC' TIPO,
        P.STATUS,
        P.PESOTOTAL,
        OT.GRUPOENTREGA,
        T.NOME TIPOENTREGA,
        COALESCE(OT.NOME, 'Operacao Logistica nao cadastrada no tipo de entrega') TABELAFRETE,
        COALESCE(R.AD_NOMEAUXILIAR, R.NOMEPARC, 'Logistica - Nao cadastrou o agente na primeira etapa de frete') TRANSPORTADORA,
--        L.NOMEPARC NOMEFANTASIA,
--        L.RAZAOSOCIAL,
        NULL NOMEFANTASIA,
        NULL RAZAOSOCIAL,
        U.UF,
        P.CODTET,
        R.CODPARC CODPARCTRANSP,
        OT.CODOPL,
        P.CODPARCUNIDPROD,
        COALESCE(U.CODUF, 0) CODUF,
        COALESCE(P.TZACONFERIDO, 'N') TZACONFERIDO,
		CASE WHEN COALESCE(P.NUDOCTER, 0) > 0 THEN 'TERCEIROS (ZAPEX)' ELSE 'GRUPO ZAP' END ORIGEMPCT
FROM TZAPCT P
         INNER JOIN TXPZAPEFESEQ S ON S.CODTET = P.CODTET
         INNER JOIN TXPZAPEFR E ON E.CODEFR = S.CODEFR
         --INNER JOIN TXPZAPOPL O ON O.CODOPL = E.CODOPL
         INNER JOIN TXPZAPTET T ON T.CODTET = P.CODTET
         LEFT JOIN TXPZAPOPL OT ON OT.CODOPL = T.CODOPL
         LEFT JOIN TGFPAR R ON R.CODPARC = E.CODPARCAGENTE
		 LEFT JOIN TSIUFS U ON U.CODUF = OT.CODUF
--         TODO: AGORA TEREMOS UMA LISTA
--         INNER JOIN TGFCAB N ON N.NUNOTA = P.NUNOTA
--         INNER JOIN TGFPAR L ON L.CODPARC = N.CODPARC
WHERE S.SEQUENCIA = (
    SELECT MIN(SEQUENCIA)
    FROM TXPZAPEFESEQ X
    WHERE X.CODTET = S.CODTET
)
AND  ((P.NUDOCTER IS NOT NULL OR P.NUDOCTER = 0 OR EXISTS (
        SELECT 1
        FROM TZAPCT_TGFCAB PCT_CAB
        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = CASE WHEN PCT_CAB.NOTAPRINCIPAL = 'S' THEN
                                                 COALESCE(PCT_CAB.NUNOTAREMESSA, PCT_CAB.NUNOTAASSOCIADA)
                                              ELSE
                                                 COALESCE(PCT_CAB.NUNOTAASSOCIADA, PCT_CAB.NUNOTAREMESSA)
                                              END
        WHERE PCT_CAB.NUPCT = P.NUPCT
        AND CAB.STATUSNFE = 'A'
)) OR EXISTS (
        SELECT 1
        FROM TZAPCT_TGFCAB PCT_CAB
        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = PCT_CAB.NUNOTASERVICO
        WHERE PCT_CAB.NUPCT = P.NUPCT
        AND PCT_CAB.NUNOTAREMESSA IS NULL
        AND PCT_CAB.NUNOTASERVICO IS NOT NULL))
UNION ALL
SELECT
        '0000000000-' || TO_CHAR(P.NUPTA, 'FM0000000000') NROUNICO,
        P.NUPTA CODIGO,
        P.DTCRIACAO,
        P.DHEFETIVADO DTFATUR,
        'PT' TIPO,
        P.STATUS,
        P.PESOTOTAL,
        OT.GRUPOENTREGA,
        T.NOME TIPOENTREGA,
        COALESCE(OT.NOME, 'Operacao Logistica nao cadastrada no tipo de entrega') TABELAFRETE,
        COALESCE(R.AD_NOMEAUXILIAR ,R.NOMEPARC, 'Logistica - Nao cadastrou o agente na primeira etapa de frete') TRANSPORTADORA,
        'VARIOS' NOMEFANTASIA,
        'VARIOS' RAZAOSOCIAL,
        U.UF,
        P.CODTET,
        R.CODPARC CODPARCTRANSP,
        OT.CODOPL,
        P.CODPARC CODPARCUNIDPROD,
        COALESCE(U.CODUF, 0) CODUF,
        COALESCE(P.TZACONFERIDO, 'N') TZACONFERIDO,
		'VARIOS' ORIGEMPCT
FROM TZAPTA P
         INNER JOIN TXPZAPEFESEQ S ON S.CODTET = P.CODTET
         INNER JOIN TXPZAPEFR E ON E.CODEFR = S.CODEFR
         --INNER JOIN TXPZAPOPL O ON O.CODOPL = E.CODOPL
         INNER JOIN TXPZAPTET T ON T.CODTET = P.CODTET
         LEFT JOIN TXPZAPOPL OT ON OT.CODOPL = T.CODOPL
         LEFT JOIN TGFPAR R ON R.CODPARC = E.CODPARCAGENTE
		 LEFT JOIN TSIUFS U ON U.CODUF = OT.CODUF
WHERE S.SEQUENCIA = (
                        SELECT MIN(SEQUENCIA)
                        FROM TXPZAPEFESEQ X
                        WHERE X.CODTET = S.CODTET
                    )
;